version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - ls
      - ls gradlew
      - ls prebuilt
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
